### ISSUE TITLE
npm run ebuild does not work

### ISSUE THREAD

**Issue by anjayluh** [popupbits/react-electron#5]
When i follow the same ebuild commande i get this error
"ebuild": "npm build && node_modules/.bin/build",
When I run npm run ebuild I get this error
> bou-backoffice@0.1.0 ebuild C:\Users\angella.LABOREMUS\Desktop\Roadmap\roadmap 2020\React\bou_backoffice
> npm build && node_modules/.bin/build

npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bou-backoffice@0.1.0 ebuild: `npm build && node_modules/.bin/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bou-backoffice@0.1.0 ebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\angella.LABOREMUS\AppData\Roaming\npm-cache\_logs\2020-05-26T09_37_21_588Z-debug.log

**Comment by lohanidamodar** [comment]
@anjayluh Please you need to update for latest react js version, please Follow my youtube tutorial on how to do that
https://www.youtube.com/watch?v=JrARTsX2RM0

As I am not currently working with electron, this is not updated to the latest version.
After following the tutorial, if you have any problems, feel free to reopen the issue and get back to me, I will try to help if I can :)
